input_dir: 'origin_data/batch2'  # 输入的根文件夹，里面所有的mp4都会被处理
output_dir: 'martial_data'  # 输出的根文件夹，会保留输入文件夹的结构
device: [0, 2]  # 可用的gpu
process_num: 3  # 每张gpu固定启动的进程数

# 是否使用该功能
split: true  # 建议使用
gvhmr: true
detect_float: true
detect_leg: true
fix_leg: false
detect_inpenet: true
fix_inpenet: false
